### ISSUE TITLE
jdftx fails to build with libxc-7.0.0

### ISSUE THREAD

**Issue by yurivict** [shankar1729/jdftx#421]
```
In file included from /usr/ports/science/jdftx/work/jdftx-1.7.0/jdftx/commands/elec_ex_corr.cpp:79:
/usr/ports/science/jdftx/work/.build/xcMap.h:5:2: error: use of undeclared identifier 'XC_MGGA_X_B00'
    5 |         XC_MGGA_X_B00, "mgga-x-b00",
      |         ^
/usr/ports/science/jdftx/work/.build/xcMap.h:55:2: error: use of undeclared identifier 'XC_GGA_X_C09X'
   55 |         XC_GGA_X_C09X, "gga-x-c09x",
      |         ^
/usr/ports/science/jdftx/work/.build/xcMap.h:56:2: error: use of undeclared identifier 'XC_GGA_X_ITYH_PBE'
   56 |         XC_GGA_X_ITYH_PBE, "gga-x-ityh-pbe",
      |         ^
/usr/ports/science/jdftx/work/.build/xcMap.h:57:2: error: use of undeclared identifier 'XC_MGGA_X_TLDA'
   57 |         XC_MGGA_X_TLDA, "mgga-x-tlda",
      |         ^
/usr/ports/science/jdftx/work/.build/xcMap.h:58:2: error: use of undeclared identifier 'XC_MGGA_X_GDME_NV'
   58 |         XC_MGGA_X_GDME_NV, "mgga-x-gdme-nv",
      |         ^
/usr/ports/science/jdftx/work/.build/xcMap.h:59:2: error: use of undeclared identifier 'XC_GGA_X_EB88'
   59 |         XC_GGA_X_EB88, "gga-x-eb88",
      |         ^
/usr/ports/science/jdftx/work/.build/xcMap.h:60:2: error: use of undeclared identifier 'XC_HYB_GGA_X_N12_SX'
   60 |         XC_HYB_GGA_X_N12_SX, "hyb-gga-x-n12-sx",
      |         ^
/usr/ports/science/jdftx/work/.build/xcMap.h:61:2: error: use of undeclared identifier 'XC_GGA_X_FT97_A'
   61 |         XC_GGA_X_FT97_A, "gga-x-ft97-a",
      |         ^
/usr/ports/science/jdftx/work/.build/xcMap.h:62:2: error: use of undeclared identifier 'XC_GGA_X_FT97_B'
   62 |         XC_GGA_X_FT97_B, "gga-x-ft97-b",
      |         ^
/usr/ports/science/jdftx/work/.build/xcMap.h:63:2: error: use of undeclared identifier 'XC_MGGA_X_VCML'
   63 |         XC_MGGA_X_VCML, "mgga-x-vcml",
      |         ^
/usr/ports/science/jdftx/work/.build/xcMap.h:64:2: error: use of undeclared identifier 'XC_MGGA_X_RPPSCAN'
   64 |         XC_MGGA_X_RPPSCAN, "mgga-x-rppscan",
      |         ^
/usr/ports/science/jdftx/work/.build/xcMap.h:65:2: error: use of undeclared identifier 'XC_MGGA_X_MS2B'
   65 |         XC_MGGA_X_MS2B, "mgga-x-ms2b",
      |         ^
/usr/ports/science/jdftx/work/.build/xcMap.h:66:2: error: use of undeclared identifier 'XC_GGA_X_PBEINT'
   66 |         XC_GGA_X_PBEINT, "gga-x-pbeint",
      |         ^
/usr/ports/science/jdftx/work/.build/xcMap.h:67:2: error: use of undeclared identifier 'XC_GGA_X_PBE'
   67 |         XC_GGA_X_PBE, "gga-x-pbe",
      |         ^
/usr/ports/science/jdftx/work/.build/xcMap.h:68:2: error: use of undeclared identifier 'XC_HYB_MGGA_X_REVSCAN0'
   68 |         XC_HYB_MGGA_X_REVSCAN0, "hyb-mgga-x-revscan0",
      |         ^
/usr/ports/science/jdftx/work/.build/xcMap.h:69:2: error: use of undeclared identifier 'XC_GGA_X_EV93'
   69 |         XC_GGA_X_EV93, "gga-x-ev93",
      |         ^
/usr/ports/science/jdftx/work/.build/xcMap.h:70:2: error: use of undeclared identifier 'XC_GGA_X_PBE_JSJR'
   70 |         XC_GGA_X_PBE_JSJR, "gga-x-pbe-jsjr",
      |         ^
/usr/ports/science/jdftx/work/.build/xcMap.h:71:2: error: use of undeclared identifier 'XC_GGA_X_PBE_ERF_GWS'
   71 |         XC_GGA_X_PBE_ERF_GWS, "gga-x-pbe-erf-gws",
      |         ^
/usr/ports/science/jdftx/work/.build/xcMap.h:72:2: error: use of undeclared identifier 'XC_GGA_X_SSB_SW'
   72 |         XC_GGA_X_SSB_SW, "gga-x-ssb-sw",
      |         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

Version: 1.7.0
FreeBSD 15 STABLE

**Comment by shankar1729** [comment]
Fixed in 22d7b69.

Seems like LibXC changed whether a specific header was included from xc.h from 6.* to 7.*.
